  version : "3"
  services:

    eureka-service:
      image: eurekaservice-app
      build: eureka (1)/
      restart: always
      network_mode: host
      container_name: eureka-service-docker
      ports:
        - "8761:8761"
      expose:
        - 8761

    mongo:
      image: mongo
      ports:
        - "27017:27017"
      container_name: mongo
      network_mode: host

    spring-config-server:
      image: configservice-app
      build: config-server/
      restart: always
      network_mode: host
      container_name: config-service
      ports:
        - "8888:8888"
      expose:
        - 8888
    api-gateway-service:
      image: apigatewayservice-app
      build: api-gateway/
      restart: always
      network_mode: host
      container_name: apigateway-service-docker
      ports:
        - "8085:8085"
      expose:
        - 8085
    muzizapplication:
      image: trackservice-app
      build: music/
      restart: always
      network_mode: host
      container_name: track-service-docker
      depends_on:
        - mongo
        - spring-config-server
      ports:
        - "8080:8080"
      expose:
        - 8080
  
